sudo: required

language: go 

go:
  - "1.8.3"

services:
  - docker

before_install:
  - chmod +x deploy.sh

script:
  - docker build -t rtfa-backend . $(printenv | grep -E '^IMAGE_' | sed 's/IMAGE_/ENV\ /g')

after_success:
  ./deploy.sh